# permissions to do viewer playgrounds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playground-viewer-role
rules:
- apiGroups:
  - app.tjololo.net
  resources:
  - playgrounds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.tjololo.net
  resources:
  - playgrounds/status
  verbs:
  - get
